name: meow_track
description: "DESIGN OF AN AUGMENTED REALITY MOBILE APP FOR CAT OWNERS"
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  http: ^1.2.2
  fl_chart: ^0.70.2
  image_picker: ^1.2.2
  firebase_storage: ^12.4.10
  qr_flutter: ^4.1.0
  file_picker: ^8.1.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  firebase_remote_config: ^6.0.0
  google_generative_ai: ^0.4.5
  speech_to_text: ^7.0.0
  country_picker: ^2.0.28
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  google_places_flutter: ^2.1.1
  cached_network_image: ^3.4.1
  google_mlkit_subject_segmentation: ^0.0.3
  image: ^4.8.0
  path_provider: ^2.1.6
  intl: ^0.20.2
  mobile_scanner: ^7.2.0
  flutter_image_compress: ^2.4.0
  sqflite: 2.3.3+1
  flutter_secure_storage: ^9.2.4
  flutter_jailbreak_detection: ^1.3.0
  flutter_dotenv: ^5.2.1
  showcaseview: ^3.0.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  # Menggunakan gambar yang sama tetapi sistem akan cuba mengecilkan jika kita tentukan ia sebagai foreground
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/animations/
    # SVG icons
    - assets/icons/
    - assets/rank/

  fonts:
    - family: Yorkmade
      fonts:
        - asset: assets/fonts/yorkmade.regular.otf
