org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
kotlin.incremental=false
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
# Tutup K2 untuk kestabilan Kotlin 1.9
kotlin.experimental.tryK2=false
# Gunakan RAM dan CPU optimum (Unity ditutup)
android.enableResourceOptimizations=true
# Abaikan amaran versi Kotlin untuk kestabilan
kotlin.jvm.target.validation.mode=warning
