import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:go_router/go_router.dart';

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: SvgPicture.asset('assets/icons/Back.svg', width: 24, height: 24, colorFilter: const ColorFilter.mode(Color(0xFF985BEF), BlendMode.srcIn)),
          onPressed: () => context.pop(),
        ),
        title: const Text("Privacy Policy", style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(25.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildTitle("Privacy Policy"),
            _buildLastUpdated("Last updated: June 18, 2026"),
            const SizedBox(height: 20),
            _buildParagraph(
                "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You."),
            _buildParagraph(
                "We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy."),
            
            _buildHeader("Interpretation and Definitions"),
            _buildSubHeader("Interpretation"),
            _buildParagraph(
                "The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."),
            
            _buildSubHeader("Definitions"),
            _buildParagraph("For the purposes of this Privacy Policy:"),
            _buildBulletPoint("Account means a unique account created for You to access our Service or parts of our Service."),
            _buildBulletPoint("Application refers to Meowtrack, the software program provided by the Company."),
            _buildBulletPoint("Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Privacy Policy) refers to Meowtrack."),
            _buildBulletPoint("Country refers to: Malaysia"),
            _buildBulletPoint("Device means any device that can access the Service such as a computer, a cell phone or a digital tablet."),
            _buildBulletPoint("Personal Data (or 'Personal Information') is any information that relates to an identified or identifiable individual."),
            _buildBulletPoint("Service refers to the Application."),
            _buildBulletPoint("Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself."),
            
            _buildHeader("Collecting and Using Your Personal Data"),
            _buildSubHeader("Types of Data Collected"),
            _buildSubHeader("Personal Data", isTertiary: true),
            _buildParagraph("While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:"),
            _buildBulletPoint("Email address"),
            _buildBulletPoint("First name and last name"),
            _buildBulletPoint("Phone number"),
            
            _buildSubHeader("Usage Data", isTertiary: true),
            _buildParagraph("Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, and other diagnostic data."),
            
            _buildSubHeader("Information Collected while Using the Application", isTertiary: true),
            _buildParagraph("While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:"),
            _buildBulletPoint("Information regarding your location"),
            _buildBulletPoint("Pictures and other information from your Device's camera and photo library"),
            
            _buildHeader("Use of Your Personal Data"),
            _buildParagraph("The Company may use Personal Data for the following purposes:"),
            _buildBulletPoint("To provide and maintain our Service, including to monitor the usage of our Service."),
            _buildBulletPoint("To manage Your Account: to manage Your registration as a user of the Service."),
            _buildBulletPoint("To contact You: By email, telephone calls, SMS, or push notifications regarding updates or informative communications."),
            _buildBulletPoint("To manage Your requests: To attend and manage Your requests to Us."),
            
            _buildHeader("Retention of Your Personal Data"),
            _buildParagraph("The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations."),
            
            _buildHeader("Delete Your Personal Data"),
            _buildParagraph("You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service."),
            
            _buildHeader("Contact Us"),
            _buildParagraph("If you have any questions about this Privacy Policy, You can contact us:"),
            _buildBulletPoint("By email: 4243003121@student.unisel.edu.my"),
            const SizedBox(height: 50),
          ],
        ),
      ),
    );
  }

  Widget _buildTitle(String text) {
    return Text(text, style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.black));
  }

  Widget _buildLastUpdated(String text) {
    return Padding(
      padding: const EdgeInsets.only(top: 8.0),
      child: Text(text, style: const TextStyle(fontSize: 14, color: Colors.grey, fontWeight: FontWeight.w500)),
    );
  }

  Widget _buildHeader(String text) {
    return Padding(
      padding: const EdgeInsets.only(top: 30.0, bottom: 15.0),
      child: Text(text, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: Color(0xFF985BEF))),
    );
  }

  Widget _buildSubHeader(String text, {bool isTertiary = false}) {
    return Padding(
      padding: const EdgeInsets.only(top: 20.0, bottom: 10.0),
      child: Text(text, style: TextStyle(fontSize: isTertiary ? 16 : 18, fontWeight: FontWeight.bold, color: Colors.black87)),
    );
  }

  Widget _buildParagraph(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 15.0),
      child: Text(text, style: const TextStyle(fontSize: 14, height: 1.6, color: Colors.black87)),
    );
  }

  Widget _buildBulletPoint(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10.0, left: 10.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text("• ", style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: Color(0xFF985BEF))),
          Expanded(child: Text(text, style: const TextStyle(fontSize: 14, height: 1.5, color: Colors.black87))),
        ],
      ),
    );
  }
}
